annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: support
      url: https://github.com/keptn/lifecycle-toolkit/issues/new
    - name: community
      url: https://slack.keptn.sh/
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Full Lifecycle
apiVersion: v2
appVersion: v2.0.0
dependencies:
- name: common
  repository: https://charts.lifecycle.keptn.sh
  version: 0.2.1
description: A Helm chart for Keptn Lifecycle Operator, a subproject of Keptn
home: https://keptn.sh
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/keptn/icon/color/keptn-icon-color.svg
keywords:
- cloud-native
- lifecycle
- lifecycle-management
- application-lifecycle
- application-lifecycle-management
- orchestration
- keptn
- operator
- pre-deployment
- post-deployment
kubeVersion: '>= 1.27.0-0'
name: keptn-lifecycle-operator
sources:
- https://github.com/keptn/lifecycle-toolkit
type: application
version: 0.6.0
