---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-system-cluster-reconciler
  labels:
    app.kubernetes.io/part-of: flux
rules:
  # Allow Flux to manage Keptn RBAC resources
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # Allow Flux to manage Roles/RoleBindings in any namespace
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-system-cluster-reconciler
  labels:
    app.kubernetes.io/part-of: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-system-cluster-reconciler
subjects:
  - kind: ServiceAccount
    name: keptn-system
    namespace: keptn-system
