{
 "title": "Keptn Overview",
 "tags": [ "keptn" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Keptn Deployment Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(keptn_deployment_count[5m])",
     "legendFormat": "{{namespace}}/{{workload}}"
    }
   ]
  },
  {
   "title": "Keptn Deployment Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "keptn_deployment_duration_seconds",
     "legendFormat": "{{namespace}}/{{workload}}"
    }
   ]
  },
  {
   "title": "Keptn Applications",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(keptn_app_count) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Deployment Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (keptn_deployment_status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}