---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lifecycle-operator-metrics
  namespace: keptn-system
  labels:
    app.kubernetes.io/name: lifecycle-operator
    release: prom
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lifecycle-operator
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-operator
  namespace: keptn-system
  labels:
    app.kubernetes.io/name: metrics-operator
    release: prom
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-operator
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
