apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: keptn-deploy
  namespace: keptn-system
spec:
  interval: 5m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/lfarizav/keptn-deploy.git
