apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keptn
  namespace: keptn-system
spec:
  interval: 10m0s
  timeout: 10m0s
  chart:
    spec:
      chart: ./helm/charts/keptn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: keptn-deploy
      version: '*'
  install:
    timeout: 10m0s
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    timeout: 10m0s
    remediation:
      retries: 3
      remediateLastFailure: true
    crds: CreateReplace
    cleanupOnFail: true
  uninstall:
    timeout: 5m
  driftDetection:
    mode: enabled
  valuesFrom:
  - kind: ConfigMap
    name: keptn-observability-config
    valuesKey: values.yaml
    optional: true
