apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- keptn-helmrelease.yaml
- keptn-tasks-helmrelease.yaml
- keptn-tasks-rbac.yaml
- keptn-gitrepository.yaml
# KeptnConfig will be added after Keptn is deployed
# - keptn-config.yaml
- keptn-observability-configmap.yaml
- keptn-servicemonitor.yaml
- dashboards/
# Slack notifications centralized in k8s-open5gs-fleet/projects/base/shared/

