apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: keptn-system
    kustomize.toolkit.fluxcd.io/namespace: keptn-system
  name: slack-notif
  namespace: keptn-system
spec:
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: HelmRelease
    name: '*'
  providerRef:
    name: slack

